=== Karniyarik/karniyarik/karniyarik-web/src/main/webapp/datafeed/xsd/car.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" 
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="arabalar" type="arabalarType"/>
  <xs:complexType name="arabaType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
    	<xs:element type="xs:string" name="id" minOccurs="0" maxOccurs="1"/>
    	<xs:element type="xs:string" name="isim" minOccurs="1" maxOccurs="1"/>
    	<xs:element type="xs:string" name="marka" minOccurs="1" maxOccurs="1"/>
    	<xs:element type="xs:double" name="fiyat" minOccurs="1" maxOccurs="1"/>
    	<xs:element type="birimType" name="birim" minOccurs="1" maxOccurs="1"/>
    	<xs:element type="xs:string" name="kategori" minOccurs="0" maxOccurs="1"/>
    	<xs:element type="xs:anyURI" name="url" minOccurs="1" maxOccurs="1"/>
    	<xs:element type="xs:anyURI" name="resim" minOccurs="0" maxOccurs="1"/>
    	<xs:element name="modelyili" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
    	<xs:element name="motorgucu" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
    	<xs:element name="motorhacmi" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
    	<xs:element name="kilometre" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
    	<xs:element name="yakit_tipi" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    	<xs:element name="renk" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    	<xs:element name="vites_tipi" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    	<xs:element name="sehir" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="arabalarType">
    <xs:sequence>
      <xs:element type="arabaType" name="araba" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="birimType">
  	<xs:restriction base="xs:string">
  		<xs:enumeration value="USD"></xs:enumeration>
  		<xs:enumeration value="TL"></xs:enumeration>
  		<xs:enumeration value="EUR"></xs:enumeration>
  		<xs:enumeration value="JPY"></xs:enumeration>
  	</xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Karniyarik/karniyarik/karniyarik-web/src/main/webapp/datafeed/sample/araba.xml
<?xml version="1.0" encoding="UTF-8"?>
<arabalar xmlns="http://www.karniyarik.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.karniyarik.com/datafeed/xsd/car.xsd">
	
	<araba>
		<isim>Satılık İkinci El Oto Porsche 911 Turbo</isim>
		<marka>Porsche</marka>
		<fiyat>177500.00</fiyat>
		<birim>EUR</birim>
		<id></id>
		<kategori></kategori>
		<url>http://www.test.com/araba/porsche-911-turbo/44149/</url>
		<resim>http://www.test.com/img/cars/6068689227.JPG</resim>
		<kilometre>25000</kilometre>
		<modelyili>2008</modelyili>
		<motorgucu>480</motorgucu>
		<motorhacmi>4000</motorhacmi>
		<renk>Siyah</renk>
		<sehir>İstanbul</sehir>
		<vites_tipi>Otomatik</vites_tipi>
		<yakit_tipi>Benzin</yakit_tipi>		
	</araba>
</arabalar>
