=== Karniyarik/karniyarik/karniyarik-web/src/main/webapp/datafeed/xsd/otel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" 
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="oteller" type="otellerType"/>
  <xs:complexType name="otelType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
        	<xs:element type="xs:string" name="id" minOccurs="0"
        		maxOccurs="1" />
        	<xs:element type="xs:string" name="isim" minOccurs="1"
        		maxOccurs="1" />
        	<xs:element type="xs:double" name="fiyat" minOccurs="1"
        		maxOccurs="1" />
        	<xs:element type="birimType" name="birim" minOccurs="1"
        		maxOccurs="1" />
        	<xs:element type="xs:string" name="kategori" minOccurs="0"
        		maxOccurs="1" />
        	<xs:element type="xs:anyURI" name="url" minOccurs="1"
        		maxOccurs="1" />
        	<xs:element type="xs:anyURI" name="resim" minOccurs="0"
        		maxOccurs="1" />
        	<xs:element name="adres" type="xs:string" minOccurs="1"
        		maxOccurs="1" />
        	<xs:element name="posta_kodu" type="xs:string" minOccurs="1"
        		maxOccurs="1">
        	</xs:element>
        	<xs:element name="sehir" type="xs:string" minOccurs="1"
        		maxOccurs="1">
        	</xs:element>
        	<xs:element name="ulke" type="xs:string" minOccurs="1"
        		maxOccurs="1">
        		<xs:annotation>
        			<xs:documentation>
        				ISO 3166-1 Ülke Kodlarından iki haneli alpha-2
        				kodlarını kullanınız bknz:
        				http://en.wikipedia.org/wiki/ISO_3166-1 bknz:
        				http://www.karniyarik.com/datafeed/xsd/ISOCountryCodeType-V2006.xsd
        			</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="yildiz" type="xs:int" minOccurs="1"
        		maxOccurs="1">
        	</xs:element>
        	<xs:element name="lat" type="xs:double" minOccurs="1"
        		maxOccurs="1">
        	</xs:element>
        	<xs:element name="lon" type="xs:double" minOccurs="1"
        		maxOccurs="1">
        	</xs:element>
        	<xs:element name="rating" type="xs:double" minOccurs="0"
        		maxOccurs="1">
        	</xs:element>
        	<xs:element name="aciklama" type="xs:string" minOccurs="1"
        		maxOccurs="1">
        	</xs:element>
        	<xs:element name="ozellikler" type="ozellikType"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="otellerType">
    <xs:sequence>
      <xs:element type="otelType" name="otel" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="birimType">
  	<xs:restriction base="xs:string">
  		<xs:enumeration value="USD"></xs:enumeration>
  		<xs:enumeration value="TL"></xs:enumeration>
  		<xs:enumeration value="EUR"></xs:enumeration>
  		<xs:enumeration value="JPY"></xs:enumeration>
  	</xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ozellikType">
  	<xs:sequence>
  		<xs:element name="ozellik" type="xs:string" maxOccurs="unbounded" minOccurs="0"></xs:element>
  	</xs:sequence>
  </xs:complexType>
</xs:schema>

=== Karniyarik/karniyarik/karniyarik-web/src/main/webapp/datafeed/sample/otel.xml
<?xml version="1.0" encoding="UTF-8"?>
<oteller xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.karniyarik.com/datafeed/xsd/otel.xsd">
  <otel>
    <id>20144883</id>
    <isim>Vicenza Hotel</isim>
	<fiyat>55</fiyat>
	<birim>EUR</birim>
	<kategori></kategori>
	<url>http://www.booking.com/hotel/tr/vicenza.html</url>
	<resim>http://aff.bstatic.com/images/hotel/org/132/1323537.jpg</resim>
	<adres>Fevziye Caddesi. No:3</adres>
	<posta_kodu>34470</posta_kodu>
	<sehir>İstanbul</sehir>
	<ulke>tr</ulke>
	<yildiz>4</yildiz>
	<lat>28.9571499824524</lat>
	<lon>41.012304800909</lon>
	<rating>3.8</rating>
	<aciklama>Just a short walk from Istanbul's historic sites, Vicenza Hotel offers quality accommodation with free wireless internet and superb sunset views from its rooftop pool area.</aciklama>
	<ozellikler>
		<ozellik>Market</ozellik>
		<ozellik>Türk Hamamı</ozellik>
		<ozellik>Çocuk Havuzu</ozellik>
	</ozellikler>
  </otel>
</oteller>
